"use client";
import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  value: null,
};

const groupInfoSlice = createSlice({
  name: "groupinfo",
  initialState,
  reducers: {
    groupInfo(state, action) {
      state.value = action.payload;
    },
  },
});

// export the actions generated by counterslice
export const { groupInfo } = groupInfoSlice.actions;
// export the reducer that generated
export default groupInfoSlice.reducer;
